api:
  model: ""
  base_url: ""
  api_key: ""
file:
  file_path: "../example/dataset/dataset.json"
  main_theme: "科普知识"
  save_dir: "../example/result"
  save_file_name: "json_file_demo_QA.json"
generation:
  method: "genQA"
  concurrent_api_requests_num: 1
  is_structure_data: True  # 表示输入文件是结构化数据
  text_template: "【标题】: {title}\n{source}在{date}提出：\n{content}"  # JSON 数据的格式模板