api:
  model: ""
  base_url: ""
  api_key: ""
file:
  file_path: "../example/dataset/Olympics.txt"
  main_theme: "巴黎奥运会"
generation:
  method: "genQA"
  concurrent_api_requests_num: 1
  save_dir: "../example/result"
  save_file_name: "single_file_demo_QA.json"